### ISSUE TITLE
Purge receiver link?

### ISSUE THREAD

**Issue by ezra-chu** [mbroadst/amqp10-link-cache#4]
Can you provide rationale for purging receiver links? 

Maybe I am missing something. I have a worker that runs an ETL process upon receiving a message, then sends a message downstream to signal completion. Purging receiver link after TTL breaks my ETL worker after TTL. 

It makes sense for me to cache a sender (two processes finish within 5s, broker timeout), it may make sense to cache the receiver (for dynamic receivers or to enforce singleton on startup), but I'm not quite sure how it makes sense to purge a receiver.

**Comment by mbroadst** [comment]
@chuej the short answer is "because it was easy" 😄 Initially this was an example plugin, but I was actually using it in a larger project for caching sender links explicitly. I agree with you that the general expectation would be that while receiver links can be cached they should certainly not be purged.

I saw you submitted a PR for this, and have some comments about that, but I'll keep that discussion over there.

**Comment by ezra-chu** [comment]
Addressed in #7.
